sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSHK4Fj6sLhp38iMf6H
    access-key-secret: dtINH693Q2OeAOxeI54Yu4BhBy8N8k
    bucket-name: xuanyuy
  redis:
    host: localhost
    port: 6379
    password: 
    database: 10
  wechat:
    appid: wx3ef64e657f266102
    secret: a297f37e72101aab4a979a8bae882c2b
    notifyUrl: https://396b571e.r19.cpolar.top -> http://localhost:8080
    refundNotifyUrl: http://396b571e.r19.cpolar.top -> http://localhost:8080
  shop:
    address: 深圳市龙岗区龙翔大道2188号

  baidu:
    ak: 4GQxBPGqMTpryQkNlRbNdVGqKbwe9Q9N